plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // ModMenu
    modImplementation "com.terraformersmc:modmenu:11.0.3"

    implementation project(path: ':common', configuration: 'namedElements')
    include project(':common')
}

loom {
    mixin {
        defaultRefmapName = "punchy.refmap.json"
    }
}
