plugins {
    id 'net.minecraftforge.gradle' version '6.0.+'
    id 'org.spongepowered.mixin' version '0.7.38'
}

minecraft {
    mappings channel: 'official', version: project.minecraft_version

    // copyIdeResources = true // often needed

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                punchy {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                punchy {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources.srcDir project(':common').sourceSets.main.resources.srcDirs
sourceSets.main.java.srcDir project(':common').sourceSets.main.java.srcDirs

dependencies {
    minecraft "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
    // implementation project(':common') // Don't depend on the artifact, compile sources directly
    // We need to declare dependencies of common here if any
    implementation "com.google.code.gson:gson:2.10.1" // Example
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

mixin {
    add sourceSets.main, "punchy.refmap.json"
    config "punchy.mixins.json"
    config "punchy.client.mixins.json"
}

// tasks.named('jar', Jar) {
//    from project(':common').sourceSets.main.output
// }
