plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()

    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"

    // We can add other common dependencies here
    implementation "com.google.code.gson:gson:2.10.1"
}

loom {
    mixin {
        useLegacyMixinAp = false
    }
}
